### PR TITLE
TECH-5146 Configure Faraday default_adapter when Faraday is defined

### PR DESCRIPTION
**Pull request by leekirchhoff**
[TECH-5146](https://ringrevenue.atlassian.net/browse/TECH-5146)

Set Faraday default_adapter to :em_synchrony when start running EventMachine reactor if Faraday is defined.

### CODE REVIEW

**Review by jebentier — APPROVED** [review]
Now this is perfect! It makes sure that as soon as EMP is started, we configure faraday to the correct adapter to avoid blocking the entire reactor. Thank you for going through the thrash to get to this solution.

**Review by ColinDKelley — APPROVED** [review]
Looks good.
I hope we can also assert when we connect with Diplomat (and `defined?(EventMachine::Synchrony)`) that the default_adapter has been set to `:em_synchrony`. That would catch the case where we called `EMP.run` before requiring `faraday`.
@jebentier Sound good?

**Comment by jebentier** [comment]
@ColinDKelley  I think that assertion is a good one to have, I simply don't think that there is a good reason for that assertion to live in `Invoca::ServiceDiscovery`/`InvocaCluster`/`Diplomat`.  If anything else comes along that uses Faraday without using `Invoca::ServiceDiscovery` we will need to duplicate this effort. Which is why I'm proposing that these should be handled elsewhere like here or somewhere else.  

What would you think about having a `Faraday` middleware that logs a warning (but still allows the request through) when `defined?(EventMachine::Synchrony) && EventMachine.reactor_running? && request.adapter != :em_synchrony`?

**Review by jebentier — APPROVED** [review]

**Review by ColinDKelley — APPROVED** [review]
Looks good!

**Comment by leekirchhoff** [comment]
This approach was rejected.

**Pull request closed without merging**
